name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGION: asia-northeast1
  REPO_NAME: container-registory
  IMAGE_NAME: evogym-llm
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/${{secrets.POOL_ID }}/providers/${{ secrets.PROVIDER_ID }}"
        service_account: ${{ secrets.SERVICE_ACCOUNT_NAME }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Auth Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build image
      run: docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG .

    - name: Push image
      run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG
