name: Docker build test

on:
  pull_request:
    branches:
      - main

env:
    IMAGE_NAME: evogym-llm
    IMAGE_TAG: test-${{ github.sha }}

jobs:
  docker-build:
    name: Test / Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME }}:$IMAGE_TAG .
